[package]
name = "expr"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_expr"
path = "expr.rs"

[dependencies]
libc = "0.2.47"
onig = "4.3.1"
uucore = { path="../uucore" }

[[bin]]
name = "expr"
path = "../../uumain.rs"
