[package]
name = "dirname"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_dirname"
path = "dirname.rs"

[dependencies]
libc = "0.2.47"
uucore = { path="../uucore" }

[[bin]]
name = "dirname"
path = "../../uumain.rs"
