[package]
name = "mkdir"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_mkdir"
path = "mkdir.rs"

[dependencies]
getopts = "0.2.18"
libc = "0.2.47"
uucore = { path="../uucore" }

[[bin]]
name = "mkdir"
path = "../../uumain.rs"
