[package]
name = "nproc"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_nproc"
path = "nproc.rs"

[dependencies]
getopts = "0.2.18"
libc = "0.2.47"
num_cpus = "1.9.0"
uucore = { path="../uucore" }

[[bin]]
name = "nproc"
path = "../../uumain.rs"
