[package]
name = "readlink"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_readlink"
path = "readlink.rs"

[dependencies]
getopts = "0.2.18"
libc = "0.2.47"

[dependencies.uucore]
path = "../uucore"
features = ["fs"]

[[bin]]
name = "readlink"
path = "../../uumain.rs"
