[package]
name = "chown"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_chown"
path = "chown.rs"

[dependencies]
glob = "0.2.11"
walkdir = "2.2.7"

[dependencies.uucore]
path = "../uucore"
features = ["entries", "fs"]

[[bin]]
name = "chown"
path = "../../uumain.rs"
