[package]
name = "mknod"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_mknod"
path = "mknod.rs"

[dependencies]
getopts = "0.2.18"
libc = "0.2.47"
uucore = { path="../uucore" }

[[bin]]
name = "mknod"
path = "../../uumain.rs"
