[package]
name = "chmod"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_chmod"
path = "chmod.rs"

[dependencies]
libc = "0.2.47"
walker = "1.0.1"

[dependencies.uucore]
path = "../uucore"
features = ["mode"]

[[bin]]
name = "chmod"
path = "../../uumain.rs"
