[package]
name = "hostid"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_hostid"
path = "hostid.rs"

[dependencies]
libc = "0.2.47"
uucore = { path="../uucore" }

[[bin]]
name = "hostid"
path = "../../uumain.rs"
