[package]
name = "libstdbuf"
version = "0.0.1"
authors = []

[lib]
name = "libstdbuf"
path = "libstdbuf.rs"
# XXX: the rlib is just to prevent Cargo from spitting out a warning
crate-type = ["cdylib", "rlib"]

[dependencies]
uucore = { path="../../uucore" }
libc = "0.2.47"
cpp = "0.5.1"

[build-dependencies]
cpp_build = "0.5.1"
