[package]
name = "od"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_od"
path = "od.rs"

[dependencies]
getopts = "0.2.18"
libc = "0.2.47"
byteorder = "1.2.7"
half = "1.3.0"
uucore = { path="../uucore" }

[[bin]]
name = "od"
path = "../../uumain.rs"
