[package]
name = "chgrp"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_chgrp"
path = "chgrp.rs"

[dependencies]
walkdir = "2.2.7"

[dependencies.uucore]
path = "../uucore"
features = ["entries", "fs"]

[[bin]]
name = "chgrp"
path = "../../uumain.rs"
