[package]
name = "pathchk"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_pathchk"
path = "pathchk.rs"

[dependencies]
getopts = "0.2.18"
libc = "0.2.47"
uucore = { path="../uucore" }

[[bin]]
name = "pathchk"
path = "../../uumain.rs"
